name: Building docker image

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  creating_image:
    runs-on: ubuntu-latest
    steps:
      - name: getting the code
        uses: actions/checkout@v4

      - name: Generate Docker tag
        id: vars
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          echo "AUTO_TAG=${SHORT_SHA}-${TIMESTAMP}" >> $GITHUB_ENV

      - name: build the image
        run: docker build -t githubaction:${{ env.AUTO_TAG }} .

      - name: login to aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::354089337523:role/github-action-for-ecr
          aws-region: ap-south-1

      - name: Debug AWS credentials and ECR access
        run: |
             aws sts get-caller-identity
             aws ecr describe-repositories --region ap-south-1 || echo "No repositories or access denied"
             aws ecr get-login-password --region ap-south-1 > /tmp/ecr-pwd.txt
             echo "Got password length: $(wc -c < /tmp/ecr-pwd.txt)"
             cat /tmp/ecr-pwd.txt | docker login --username AWS --password-stdin 354089337523.dkr.ecr.ap-south-1.amazonaws.com

      - name: login to ecr
        run: |
          aws ecr get-login-password --region ap-south-1 | \
          docker login --username AWS --password-stdin 354089337523.dkr.ecr.ap-south-1.amazonaws.com

      - name: tag image for ecr
        run: |
          docker tag githubaction:${{ env.AUTO_TAG }} 354089337523.dkr.ecr.ap-south-1.amazonaws.com/githubaction:${{ env.AUTO_TAG }}
          docker tag githubaction:${{ env.AUTO_TAG }} .dkr.ecr.ap-south-1.amazonaws.com/githubaction:latest

      - name: push the image to ecr
        run: |
          docker push 354089337523.dkr.ecr.ap-south-1.amazonaws.com/githubaction:${{ env.AUTO_TAG }}
          docker push 354089337523.dkr.ecr.ap-south-1.amazonaws.com/githubaction:latest
